import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'adapters/index': 'src/adapters/index.ts',
    'frameworks/index': 'src/frameworks/index.ts',
    'agent/index': 'src/agent/index.ts',
    'cli/index': 'src/cli/index.ts',
    'mcp/index': 'src/mcp/index.ts',
  },
  format: ['esm'],
  dts: true,
  noExternal: [
    '@roadsidelab/keyspot-core',
    '@roadsidelab/keyspot-core/errors',
    '@roadsidelab/keyspot-core/circuit-breaker',
    '@roadsidelab/keyspot-core/scanner',
    '@roadsidelab/keyspot-core/taint',
    '@roadsidelab/keyspot-core/security',
    '@roadsidelab/keyspot-core/worker',
    '@roadsidelab/keyspot-core/compliance',
    '@roadsidelab/keyspot-core/adapters',
    '@roadsidelab/keyspot-core/telemetry',
    '@roadsidelab/keyspot-core/logger',
    '@roadsidelab/keyspot-vault',
    '@roadsidelab/keyspot-vault/aws',
    '@roadsidelab/keyspot-vault/circuit-breaker-adapter',
    '@roadsidelab/keyspot-patterns',
    '@roadsidelab/keyspot-adapters',
    '@roadsidelab/keyspot-frameworks',
    '@roadsidelab/keyspot-cli',
    '@roadsidelab/keyspot-agent',
    '@roadsidelab/keyspot-mcp',
  ],
  external: [
    '@pinecone-database/pinecone',
    'chromadb',
    '@qdrant/js-client-rest',
    'weaviate-ts-client',
    'lancedb',
    '@zilliz/milvus2-sdk-node',
    '@aws-sdk/client-secrets-manager',
  ],
  clean: true,
  splitting: false,
  shims: true,
});
